### ISSUE TITLE
Errorr

### ISSUE THREAD

**Issue by ghost** [TylerMcCraw/android-weather#1]
I am getting the following error

t com.w3bshark.android_weather.rest.TenDayForecastHandler.getTenDayForecast(TenDayForecastHandler.java:75)
        at com.w3bshark.android_weather.rest.TenDayForecastHandler.doInBackground(TenDayForecastHandler.java:58)
        at com.w3bshark.android_weather.rest.TenDayForecastHandler.doInBackground(TenDayForecastHandler.java:27)

**Comment by TylerMcCraw** [comment]
Could you please paste the full stacktrace?
It looks like this is just a partial copy/paste.

**Comment by ghost** [comment]
07-12 01:39:30.805 25423-25423/? E/Zygote: v2
07-12 01:39:30.805 25423-25423/? I/libpersona: KNOX_SDCARD checking this for 10350
    KNOX_SDCARD not a persona
07-12 01:39:30.806 25423-25423/? E/Zygote: accessInfo : 0
07-12 01:39:30.807 25423-25423/? W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SECMOBILE_7.0_0010, [-1 -1 -1 -1 0 1]
07-12 01:39:30.808 25423-25423/? I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.w3bshark.android_weather 
07-12 01:39:30.811 25423-25423/? I/art: Late-enabling -Xcheck:jni
07-12 01:39:30.829 25423-25430/? E/art: Failed sending reply to debugger: Broken pipe
07-12 01:39:30.829 25423-25430/? I/art: Debugger is no longer active
    Starting a blocking GC Instrumentation
07-12 01:39:31.054 25423-25423/? I/InstantRun: starting instant run server: is main process
07-12 01:39:31.356 25423-25423/? E/MainActivity: User has not given sufficient permissions for geolocation
07-12 01:39:31.361 25423-25440/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.w3bshark.android_weather, PID: 25423
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:318)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
        at com.w3bshark.android_weather.rest.TenDayForecastHandler.getTenDayForecast(TenDayForecastHandler.java:75)
        at com.w3bshark.android_weather.rest.TenDayForecastHandler.doInBackground(TenDayForecastHandler.java:58)
        at com.w3bshark.android_weather.rest.TenDayForecastHandler.doInBackground(TenDayForecastHandler.java:27)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:762) 
07-12 01:39:31.386 25423-25423/? D/Choreographer: init sf_choreo_doframe   debug_Level : 0x4f4cdebug_game_running : false
07-12 01:39:31.395 25423-25423/? D/ViewRootImpl@468312f[MainActivity]: ThreadedRenderer.create() translucent=false
07-12 01:39:31.404 25423-25423/? D/InputTransport: Input channel constructed: fd=70
07-12 01:39:31.405 25423-25423/? D/ViewRootImpl@468312f[MainActivity]: setView = DecorView@8b3733c[MainActivity] touchMode=true
07-12 01:39:31.436 25423-25423/? D/ViewRootImpl@468312f[MainActivity]: dispatchAttachedToWindow
07-12 01:39:31.460 25423-25423/? D/ViewRootImpl@468312f[MainActivity]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1080,1920] result=0x7 surface={isValid=true -545331200} surfaceGenerationChanged=true
07-12 01:39:31.461 25423-25423/? D/ViewRootImpl@468312f[MainActivity]: mHardwareRenderer.initialize() mSurface={isValid=true -545331200} hwInitialized=true
07-12 01:39:31.487 25423-25444/? I/OpenGLRenderer: Initialized EGL, version 1.4
07-12 01:39:31.487 25423-25444/? D/OpenGLRenderer: Swap behavior 1
07-12 01:39:31.493 25423-25444/? D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
07-12 01:39:31.540 25423-25423/? W/art: Before Android 4.1, method int android.support.v7.internal.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
07-12 01:39:31.636 25423-25423/? D/ViewRootImpl@468312f[MainActivity]: mHardwareRenderer.destroy()#1
07-12 01:39:31.647 25423-25423/? D/ViewRootImpl@468312f[MainActivity]: Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
07-12 01:39:40.872 25423-25423/com.w3bshark.android_weather D/ViewRootImpl@468312f[MainActivity]: mHardwareRenderer.destroy()#4
    dispatchDetachedFromWindow
07-12 01:39:40.878 25423-25423/com.w3bshark.android_weather D/InputTransport: Input channel destroyed: fd=70

**Comment by TylerMcCraw** [comment]
This seems to be due to you not giving permission to the app for the location.
See `User has not given sufficient permissions for geolocation` in your stacktrace.

I suspect this is because you're testing on a device which is on Android N or newer, in which case, you may have not allowed the app to use geolocation.
As I built this project a long time ago, it is a bit outdated and I don't have plans to update it anytime soon.
You may want to either manually set the location permission in settings or attempt to build in permissions checking into your own copy of the project.

Hope this helps.

**Comment by ghost** [comment]
On manually set the location permission in settings, it does a success build but no data is being displayed is it because there no Rest Api, which i am supposed to add ? I am fairly new android dev.

**Comment by TylerMcCraw** [comment]
There is a class for managing network requests to the Open Weather api.
That class is located here: https://github.com/TylerMcCraw/android-weather/blob/master/app/src/main/java/com/w3bshark/android_weather/rest/TenDayForecastHandler.java
If you want to continue using this project as a base, then I would suggest debugging that class to see why no data is being returned.

But, honestly, if you're looking for an even easier project to get into which uses more up-to-date standards, you should take a look at this list: https://blog.aritraroy.in/20-awesome-open-source-android-apps-to-boost-your-development-skills-b62832cf0fa4
and use this as a reference: https://github.com/JStumpp/awesome-android

This weather project uses very rudimentary standards which are outdated
